Fix:2964 obtain Postgres DB URL from ENV using branches get command
supabase/cli pull request #2996
Opened 2024-12-25 18:05 UTC by yaten2302

## What kind of change does this PR introduce?

This PR introduces a new feature to enable users to obtain the Postgres db url from the .env using the `branches get` command.

## What is the current behavior?

Fixes #2964 

## What is the new behavior?

This PR adds a new flag to the `branches get` command to help users to get the postgres db url from the env.

## Additional context

Add any other context or screenshots.

2024-12-25 18:17 UTC, yaten2302 commented
@sweatybridge , I've a doubt, that as you mentioned in [this](https://github.com/supabase/cli/issues/2964#issuecomment-2561252928) comment, that a new `--output` flag should be added to the `branches get` command. But, while implementing that, it's showing an error that the `output` flag is being redeclared. So, is it possible that instead of using the output flag, we can use a Boolean var `postgres-url`?

Also, as you mentioned, that the postgres_url and prostgres_url_non_pooling has to be added if this flag is mentioned with the command and the code can be reused from the `bootstrap` command. But, while I was checking the `writeDotEnv` func, it writes the complete thing to the .env file. But, I'm confused that how can I get the postgres_db_url from the `writeDotEnv` func? Because, I was having some issues in adding the postgres_db_url to the [`resp`](https://github.com/supabase/cli/blob/develop/internal/branches/get/get.go#L13), could you guide that how can I add the same to the resp, so that it can be used to display it on the output table for the user.

2024-12-31 18:15 UTC, yaten2302 commented
Hey @sweatybridge , could you please have a look at this PR, I've made the required changes, kindly review and LMK if any more are required!!
Thanks

2025-01-01 06:13 UTC, sweatybridge commented
Let's do this in smaller steps so I can provide more detailed guidance.

> But, while implementing that, it's showing an error that the output flag is being redeclared.

This is how golang works: any variable declared in the same package is shared by all code in that package. Since the output variable is already declared in `cmd` package, you don't need to redeclare for this command.

For your first commit, simply passing it down to branches get command will do. No need to implement the actual behaviour for env output.

After you've done that, tag me again so I can check before providing more details for the actual implementation.

2025-01-01 06:15 UTC, sweatybridge requested changes
Feel free to open a new PR if it's easier for you.

2025-01-01 06:18 UTC, sweatybridge commented
Also, sorry for the late reply as I was on holiday for the last 2 weeks and there were a lot to catch up on. I will review more promptly this week and next if you plan to make the changes.

2025-01-01 06:35 UTC, yaten2302 commented
Heyy @sweatybridge , sorry, actually, I was pushing some changes right now only and that's why didn't see your comment on this PR.

> Let's do this in smaller steps so I can provide more detailed guidance.
> 
> > But, while implementing that, it's showing an error that the output flag is being redeclared.
> 
> This is how golang works: any variable declared in the same package is shared by all code in that package. Since the output variable is already declared in `cmd` package, you don't need to redeclare for this command.
> 
> For your first commit, simply passing it down to branches get command will do. No need to implement the actual behaviour for env output.
> 
> After you've done that, tag me again so I can check before providing more details for the actual implementation.

Also, yes, for this, I was also researching about the same and now I understood that, vars are shared across the same package files in Go.
I've made some changes now, I think that these might fix this `--output-env` flag. Could you have a look at it, whenever you're free!!
Thanks :)

2025-01-01 06:41 UTC, sweatybridge commented on cmd/branches.go
> +	getFlags.BoolVar(&postgres_url, "output-env", false, "Output the Postgres URL in the table.")
We want to use an enum flag named output, not a new flag. For eg. https://github.com/supabase/cli/blob/e303c411d0722056beab59edb0b6c1117a9d156c/cmd/status.go#L44

2025-01-01 06:44 UTC, sweatybridge commented on cmd/branches.go
> +	getFlags.BoolVar(&postgres_url, "output-env", false, "Output the Postgres URL in the table.")
@yaten2302 let me know if everything is clear. The rest of this PR depends on passing down this flag correctly so I won't review further until the first part is done.

2025-01-01 07:21 UTC, yaten2302 commented on cmd/branches.go
> +	getFlags.BoolVar(&postgres_url, "output-env", false, "Output the Postgres URL in the table.")
@sweatybridge , I've pushed a commit, what I've understood is that, the `output` flag is already present and that has to be used and checked if `output == "env"`, then the postgres url should be displayed on the table, am I correct?

2025-01-01 07:29 UTC, sweatybridge commented on cmd/branches.go
> +	getFlags.BoolVar(&postgres_url, "output-env", false, "Output the Postgres URL in the table.")
Yes, but you want to check `output == utils.OutputEnv` since it's an enum. Let's make the flag change first and iterate from there.

2025-01-01 07:35 UTC, yaten2302 commented on cmd/branches.go
> +	getFlags.BoolVar(&postgres_url, "output-env", false, "Output the Postgres URL in the table.")
Got it now, made the changes 👍

2025-01-01 07:40 UTC, sweatybridge commented on cmd/branches.go
> +				}
```suggestion
```

Not needed anymore

2025-01-01 07:40 UTC, sweatybridge commented on cmd/branches.go
> +			cmdFlags := cmd.Flags()
```suggestion
```

Ditto

2025-01-01 07:42 UTC, sweatybridge commented on cmd/branches.go
> +			return get.Run(ctx, branchId, output.Value, pgconn.Config{}, afero.NewOsFs())
```suggestion
			return get.Run(ctx, branchId, output.Value, afero.NewOsFs())
```

Also no need to pass in pgconn, as we will be constructing the connection config from branch details returned from api.

2025-01-01 07:53 UTC, yaten2302 commented on cmd/branches.go
> +			return get.Run(ctx, branchId, output.Value, pgconn.Config{}, afero.NewOsFs())
@sweatybridge , but if we don't pass pgconn here, then it will give an error because in get.Run(), 5 arguments are expected, so are we gonna change the Run() func in `internal/branches/get/get.go`?

2025-01-01 07:56 UTC, sweatybridge commented on cmd/branches.go
> +			return get.Run(ctx, branchId, output.Value, pgconn.Config{}, afero.NewOsFs())
Yes, let's change the Run method to remove this arg since it's not needed.

2025-01-01 08:00 UTC, yaten2302 commented
Now, how should the Run() func be changed in `internal/branches/get/get.go` in order to get the POSTGRES_URL_NON_POOLING from the `internal/bootstrap/bootstrap.go`?

2025-01-01 08:09 UTC, sweatybridge commented on cmd/branches.go
> +	"github.com/jackc/pgconn"
```suggestion
```

Removed unused import

2025-01-01 08:09 UTC, sweatybridge commented on internal/branches/get/get.go
Here you want to instantiate pgconn.Config with params from api response. For eg

```go
config := pgconn.Config{Host: utils.GetSupabaseDbHost(resp.JSON200.DbHost)}
```

Please fill in the other fields from `resp` as well.

2025-01-01 08:23 UTC, yaten2302 commented on internal/branches/get/get.go
@sweatybridge , I've a doubt in here, that, if we pass the DbHost in `utils.GetSupabaseDbHost(resp...)`, then our result will be - `db.projectRef.supabase.co`, am I correct?
If yes, then will it not return the wrong URL, because we want [this non_pooling url](https://github.com/supabase/cli/blob/develop/internal/bootstrap/bootstrap.go#L207), to be returned?

2025-01-01 08:23 UTC, sweatybridge commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
The output fields should not change based on output format.

Since the default output format is pretty print, let's keep the old format string and simply append the newly constructed url with header `POSTGRES URL`.

2025-01-01 08:24 UTC, yaten2302 commented on internal/branches/get/get.go
Also, I've to pass this `config := pgconn.Config{Host: utils.GetSupabaseDbHost(resp.JSON200.DbHost)}`, in the `get.go`, similar to [this](https://github.com/supabase/cli/blob/develop/internal/branches/get/get.go#L21-L30), right?

2025-01-01 08:25 UTC, sweatybridge commented on internal/branches/get/get.go
`db.*.supabase.co` is the non pooling url. The url for connection pooler must be fetched separately from api.

2025-01-01 08:26 UTC, yaten2302 commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
So, like, I've don't have to change [this](https://github.com/supabase/cli/blob/develop/internal/branches/get/get.go#L32-L43), but, simply append the `POSTGRES_URL` column if `env == utils.OutputEnv`, am I right?

2025-01-01 08:28 UTC, sweatybridge commented on internal/branches/get/get.go
> Also, I've to pass this config := pgconn.Config{Host: utils.GetSupabaseDbHost(resp.JSON200.DbHost)}, in the get.go, similar to this, right?

There's no need to mask again if that's your question. As long as you instantiate at this specific line.

2025-01-01 08:30 UTC, sweatybridge commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
Don't handle OutputEnv for now. It will be too involved. Just focus on making the pretty print work as expected.

After that I will show you the code to support all output formats, including env, json, etc.

2025-01-01 08:32 UTC, yaten2302 commented on internal/branches/get/get.go
Yes, got it now 👍

2025-01-01 08:34 UTC, yaten2302 commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
I haven't added this change in the latest commit, doing it now 👍

2025-01-01 08:36 UTC, yaten2302 commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
Previously, the pretty print was like [this](https://github.com/supabase/cli/blob/develop/internal/branches/get/get.go#L32-L43), so should I first revert back to the same as given here?

2025-01-01 08:46 UTC, sweatybridge commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
> Previously, the pretty print was like this, so should I first revert back to the same as given here?

Yup, we are only appending a new column to the previous table.

2025-01-01 11:01 UTC, yaten2302 commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
I've reverted back to the previous table structure, now should I use the `env` var to check the condition and add new column accordingly?

2025-01-01 11:18 UTC, sweatybridge commented on internal/branches/get/get.go
Please add in other fields like Port, Pass, and User.

2025-01-01 11:24 UTC, sweatybridge commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
No, just add in the column unconditionally. Like this

```
	table := `|HOST|PORT|USER|PASSWORD|JWT SECRET|POSTGRES VERSION|STATUS|POSTGRES URL|
|-|-|-|-|-|-|-|-|
` + fmt.Sprintf(
```

2025-01-01 11:27 UTC, yaten2302 commented on internal/branches/get/get.go
For the other fields like port, password, user etc, can it be done by using `resp.JSON200.Port`, is this valid?

2025-01-01 11:28 UTC, yaten2302 commented on internal/branches/get/get.go
![image](https://github.com/user-attachments/assets/2b9b763b-c484-43b4-850e-163f7d496b81)

2025-01-01 11:31 UTC, sweatybridge commented on internal/branches/get/get.go
Yes, you are on the right track. There are convenience methods in cast.go to help you convert from between different integer and pointer types safely.

Remember to format each field on a new line for readability.

2025-01-01 11:47 UTC, yaten2302 commented on internal/branches/get/get.go
![image](https://github.com/user-attachments/assets/2447ba5a-e25f-451b-82df-fb540ec79bf9)
Is this looking good?

2025-01-01 11:53 UTC, sweatybridge commented on internal/branches/get/get.go
Let's move Host: to a new line as well.

I think casting to uint is unnecessary. Your previous solution `uint16(port)` should be fine.

The rest looks ok from screenshot.

2025-01-01 11:57 UTC, yaten2302 commented on internal/branches/get/get.go
Made the changes 👍 
![image](https://github.com/user-attachments/assets/ba556b55-a979-4f0d-bdf4-f98a4835491d)

2025-01-01 14:24 UTC, yaten2302 commented on internal/branches/get/get.go
May I push this change if it looks good?

2025-01-01 14:26 UTC, yaten2302 commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
But, if we add this column and the user hasn't specified the `-o` flag, then this will still be shown (but with nil value), will this not look somewhat odd?

2025-01-01 14:39 UTC, sweatybridge commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
You are misunderstanding what the `-o` flag does. It should format all fields using one of the supported encoding, ie. json or .env. It is not meant to be appending or removing fields from the tabular output.

2025-01-01 14:40 UTC, sweatybridge commented on internal/branches/get/get.go
Feel free to push it and I will take another look.

2025-01-01 16:02 UTC, sweatybridge commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
For eg. this is how branches get command should eventually be implemented https://github.com/supabase/cli/blob/7a513e346ab55ad2e3a90a8675445121b66c3761/internal/projects/list/list.go#L44

2025-01-01 17:11 UTC, yaten2302 commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
Ohh, yes, okay, I think now I got it, as mentioned [here](https://supabase.com/docs/reference/cli/supabase-status), the `-o` flag gives the format in which the output should be shown to the user, am I right? And the table here mentioned is used only to render the output which has to be shown to the user. <br>
![image](https://github.com/user-attachments/assets/435361c1-bafd-43ff-8ace-3cef80e7fafb)

2025-01-01 17:13 UTC, yaten2302 commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
But, if this is the case, then how will we get to know that the user wants the DB_URL or not? Are we gonna add that irrespective of the user's preference or should a new flag be created to take into account that if the user wants the DB_URL, then it'll be shown otherwise it won't be?

2025-01-01 18:47 UTC, sweatybridge commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
> Are we gonna add that irrespective of the user's preference

Yup we want to always show the db url. I think most users want the connection string for convenience. If not, there are other ways to filter the output like piping to grep or sed.

2025-01-02 07:06 UTC, yaten2302 commented on internal/branches/get/get.go
Pushed these changes 👍

2025-01-02 07:08 UTC, yaten2302 commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
Okay, got it now 👍 
So, in the `POSTGRES URL` column in the table, we've to write - https://supabase.com/docs/guides/database/connecting-to-postgres this connection string?<br>
![image](https://github.com/user-attachments/assets/4d647672-e9c8-49fd-9438-76381df76613)

I was also checking about this on stackoverflow, I found [this](https://stackoverflow.com/questions/78455486/whats-the-correct-postgres-url-when-hosting-supabase-with-coolify).

2025-01-02 07:44 UTC, sweatybridge commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
Yes, and you can call ToPostgresURL to convert from pgconn.Config to the full connection string.

2025-01-03 07:47 UTC, yaten2302 commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
Hi, sorry for the delay, I've added the whole connection string, could you please have a look 👍

2025-01-03 07:53 UTC, sweatybridge commented on internal/branches/get/get.go
> +		"|`%s`|`%d`|`%s`|`%s`|`%s`|`%s`|`%s`|",
Looks good! Once you resolve the lint errors, we can merge and work on part 2.

2025-01-03 07:54 UTC, sweatybridge commented on internal/bootstrap/bootstrap.go
> +
Let's remove these changes for part 1.

2025-01-03 09:16 UTC, yaten2302 commented on internal/bootstrap/bootstrap.go
> +
But, if we remove this part, then it'll show an error, because nothing is being returned at the end. Instead of this, show I remove [this](https://github.com/supabase/cli/pull/2996/files/139e739d9e202ba2b70b2705eb66d1bb7f0b43a3#diff-2ff3a3bcfc0c1695c074d2a42de2b237a7e6f0e1b01ed090a57207cd4725226cR297-R303) whole part? and then add only `return value`?

2025-01-03 09:30 UTC, sweatybridge commented on internal/bootstrap/bootstrap.go
> +
I mean we don't need the entire `GetPostgresURLNonPooling` method.

In branches/get, we can serialise a map to env file like this.

```
	if utils.OutputFormat.Value != utils.OutputPretty {
		envs := map[string]string{
			"POSTGRES_URL": postgresConnectionString,
		}
		return utils.EncodeOutput(utils.OutputFormat.Value, os.Stdout, envs)
	}
```

2025-01-03 09:31 UTC, sweatybridge commented on internal/branches/get/get.go
> +func Run(ctx context.Context, branchId string, env string, fsys afero.Fs) error {
```suggestion
func Run(ctx context.Context, branchId string, fsys afero.Fs) error {
```

2025-01-03 09:31 UTC, sweatybridge commented on cmd/branches.go
> +			return get.Run(ctx, branchId, output.Value, afero.NewOsFs())
```suggestion
			return get.Run(ctx, branchId, afero.NewOsFs())
```

2025-01-03 09:36 UTC, sweatybridge commented on internal/branches/get/get.go
> +	postgresConnectionString := utils.ToPostgresURL(config)
```suggestion
	postgresConnectionString := utils.ToPostgresURL(config)

	if utils.OutputFormat.Value != utils.OutputPretty {
		envs := map[string]string{
			"POSTGRES_URL": postgresConnectionString,
		}
		return utils.EncodeOutput(utils.OutputFormat.Value, os.Stdout, envs)
	}

```

2025-01-03 09:40 UTC, yaten2302 commented on internal/branches/get/get.go
> +	postgresConnectionString := utils.ToPostgresURL(config)
Already made this change 👍

2025-01-03 09:46 UTC, sweatybridge commented on cmd/branches.go
> +	getFlags.VarP(&output, "output", "o", "Output format of branch details.")
```suggestion
	getFlags.VarP(&utils.OutputFormat, "output", "o", "Output format of branch details.")
```

2025-01-03 09:46 UTC, sweatybridge commented on internal/branches/get/get.go
> +	envs := map[string]string{}
```suggestion
```

2025-01-04 03:47 UTC, sweatybridge commented on internal/branches/get/get.go
> +		Port: uint16(resp.JSON200.DbPort),
```suggestion
		Port: uint16(cast.IntToUint(resp.JSON200.DbPort)),
```

To fix lint check

2025-01-04 08:18 UTC, sweatybridge commented on internal/branches/get/get.go
> +		Port: uint16(resp.JSON200.DbPort),
@yaten2302 in case you missed it, there are more linter errors to fix https://github.com/supabase/cli/actions/runs/12608039666

2025-01-04 11:01 UTC, yaten2302 commented on internal/branches/get/get.go
> +		Port: uint16(resp.JSON200.DbPort),
@sweatybridge , yes, ig I forgot about the linter errors, I've a doubt, that in [here](https://github.com/supabase/cli/pull/2996/files#annotation_30429263353), these 2 errors are being show <br>
![image](https://github.com/user-attachments/assets/8bea13b4-42b4-41e3-8ece-64e803fb87c1)

In the 2nd one, should I remove `cast.IntToUInt(...)`, I think the error is arising because of that only?
For the first one, I've pushed a commit, I think it should be fixed now (formatted the file)

2025-01-04 16:09 UTC, sweatybridge commented on internal/branches/get/get.go
> +		Port: uint16(resp.JSON200.DbPort),
> In the 2nd one, should I remove cast.IntToUInt(...), I think the error is arising because of that only?

We need to implement a new method for safely casting UInt to UInt16 and call it. You can check the existing examples in cast.go on how to check for overflows. But if you feel stuck, I can also take over from here.

2025-01-04 16:58 UTC, yaten2302 commented on internal/branches/get/get.go
> +		Port: uint16(resp.JSON200.DbPort),
I'll research upon it a and then ask if I encounter any doubts! Also, I wanted to ask that, is it possible to check the linter errors are failing or passing without pushing the changes?

2025-01-05 06:10 UTC, yaten2302 commented on internal/branches/get/get.go
> +		Port: uint16(resp.JSON200.DbPort),
Hey, I just now pushed a commit to try to fix the linter error, but unfortunately it's failing, could you please guide that is there some other file, in which some issue similar to this is being handled? I would like to understand from that and then try to implement that here.

2025-01-05 09:00 UTC, sweatybridge commented on internal/branches/get/get.go
> +		Port: uint16(resp.JSON200.DbPort),
```
// UIntToUInt16 converts a uint to an uint16, handling potential overflow
func UIntToUInt16(value uint) int {
	if value <= math.MaxUInt16 {
		return uint16(value)
	}
	return math.MaxUInt16
}
```

You want to add the above to cast.go and call it like this


```
Port: cast.UIntToUInt16(cast.IntToUInt(reps.JSON200.Port))
```

2025-01-05 10:21 UTC, yaten2302 commented on internal/branches/get/get.go
> +		Port: uint16(resp.JSON200.DbPort),
Oh, okay, got it now, thanks for your help 👍 
But, in the first line, shouldn't the return value of the `UIntToUInt16` func be `uint16`?

2025-01-05 10:32 UTC, sweatybridge approved these changes

2025-01-05 10:32 UTC, merged

2025-01-05 10:54 UTC, yaten2302 commented
Thank you so much @sweatybridge  for helping me out with this PR, this was my very first contribution with supabase, I'll definitely check out some other issues and work on them 👍