feat: support import maps in functions serve and deploy
supabase/cli pull request #662
Opened 2022-12-02 06:00 UTC by laktek

## What kind of change does this PR introduce?

This adds support for import maps in `function serve` and `function deploy`. 

What is Import Maps?

https://deno.land/manual@v1.28.3/basics/modules/import_maps

For deployed functions import_map.json should always be placed in function's top-level directory.

2022-12-02 06:11 UTC, soedirgo commented
Can we make the `import_map.json` path non-configurable? It's a bit odd that it can be set for `serve` but not `deploy`

2022-12-02 06:59 UTC, laktek commented
> Can we make the import_map.json path non-configurable? It's a bit odd that it can be set for serve but not deploy

Yup, I had the same thought after making the PR :) let's do that. So a `--import-map` flag on serve would look for the file on default location.

2022-12-05 01:07 UTC, laktek commented
@soedirgo I've updated the PR to make the `import_map.json` path to be non-configurable in serve command.

2022-12-05 04:17 UTC, soedirgo commented
Added a commit to:
- remove the option altogether and just omit the option if there's no `import_map.json`
- fix import map path to always use Unix path separator, since the container image is always assumed to be Linux

2022-12-05 07:07 UTC, sweatybridge requested changes

2022-12-05 07:07 UTC, sweatybridge commented on internal/functions/serve/serve.go
> +		if _, err := os.Stat(localImportMapPath); err == nil {
```suggestion
		if _, err := fsys.Stat(localImportMapPath); err == nil {
```

2022-12-05 07:07 UTC, sweatybridge commented on internal/functions/serve/serve.go
> +			if _, err := os.Stat(localImportMapPath); err == nil {
```suggestion
			if _, err := fsys.Stat(localImportMapPath); err == nil {
```

2022-12-05 07:09 UTC, sweatybridge commented on internal/utils/eszip/build.ts
> +        const content = await Deno.readTextFile((actualPath));
Is the inner bracket redundant?
```suggestion
        const content = await Deno.readTextFile(actualPath);
```

2022-12-05 07:53 UTC, soedirgo commented on internal/functions/serve/serve.go
> +		if _, err := os.Stat(localImportMapPath); err == nil {
Oops, thanks!

2022-12-05 07:55 UTC, sweatybridge approved these changes

2022-12-05 08:11 UTC, laktek commented
@sweatybridge @soedirgo Just merge this PR yet. Noticed an issue with Deno Deploy config (which would affect older functions), we probably need to do a small change before releasing this.

2022-12-05 22:59 UTC, laktek commented on internal/utils/eszip/build.ts
> +        const content = await Deno.readTextFile((actualPath));
fixed in f26b4a6

2022-12-06 04:54 UTC, laktek commented
@soedirgo @sweatybridge I had to add another commit to the PR to send `import_map` param to the API when creating or updating a function. https://github.com/supabase/cli/pull/662/commits/f8279b71cc7ae0961bfbbb483a09fc44f99d4ea5 

This ensures we don't break old functions without an import map.

2022-12-06 10:19 UTC, merged